# Welcome to SkBee

settings:
  # Enable this if you would like to see more verbose debug messages
  debug: false

# Disable elements you do not plan to use.
elements:
  # Enable NBT elements
  nbt: true

  # Enable Scoreboard elements
  scoreboard: true

  # Enable Team elements
  team: true

  # Enable custom recipe elements
  recipe: true

  # Enable bound elements
  # Bounds are like custom world guard regions
  bound: true

  # Enable structure elements
  structure: true

  # Enable VirtualFurnace elements
  # This feature is semi-experimental, please use with caution
  virtual-furnace: false

  # Enable Text Component elements
  text-component: true

  # Enable pathfinding elements
  # Note: Only available on Paper
  pathfinding: true

  # Enable world creator elements
  world-creator: true
  # Whether or not custom worlds should automatically load on server start
  # If disabled, you will need to load worlds with the load world effect
  auto-load-custom-worlds: true

  # Enable Minecraft GameEvent elements
  game-event: true

  # Enable boss bar elements
  boss-bar: true

  # Enable statistic elements
  statistic: true

  # Enable villager/merchant elements
  villager: true

  # Enable advancement elements
  advancement: true

recipe:
  # This is the namespace all recipes will be saved under
  # You can choose whatever you wish
  # Example, when using the minecraft recipe command `/minecraft:recipe give playerName skbee:my_custom_recipe`
  namespace: "skbee"
