blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Skript Hub Docs
    url: https://skripthub.net/docs/
    about: Find SkBee's docs and 100's of examples on Skript Hub
  - name: ðŸ’» Skript Hub Discord
    url: https://discord.gg/da9n4S7
    about: For general help with Skript & SkBee ask in the #skript-help channel in the Skript Hub discord
  - name: ðŸš° SpigotMC Resource
    url: https://www.spigotmc.org/resources/skbee-skript-addon.75839/
    about: Read about SkBee on spigot!
